apiVersion: apps/v1
kind: Deployment
metadata:
  name: net
  namespace: net
spec:
  revisionHistoryLimit: 3
  selector:
   matchLabels:
    app: net
  replicas: 1
  template:
    metadata:
      labels:
        app: net
    spec:
      initContainers:
      - name: init-chown
        image: busybox
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          chown -R www-data:www-data /mnt/public_content &&
          chown -R www-data:www-data /mnt/private_content &&
          chmod -R 770 /mnt/public_content &&
          chmod -R 770 /mnt/private_content
        volumeMounts:
        - name: public-content
          mountPath: /mnt/public_content
        - name: private-content
          mountPath: /mnt/private_content
      imagePullSecrets:
      - name: my-docker-credentials
      containers:
      - name: net
        image: udeccolima/net:simplesaml
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ENDPOINT
          value: mysql-net
        - name: DATABASE
          value: proyecto
        - name: USERD
          value: user
        - name: PASSD
          valueFrom:
            secretKeyRef:
              name: proyecto-secret
              key: proyecto-password
        volumeMounts:
        - name: public-content
          mountPath: /var/www/net/public_content
        - name: private-content
          mountPath: /var/www/private_content
      volumes:
      - name: public-content
        persistentVolumeClaim:
          claimName: public-content-pvc
      - name: private-content
        persistentVolumeClaim:
          claimName: private-content-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: net
  namespace: net
  labels:
    app: net
spec:
  selector:
   app: net
  type: ClusterIP
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80