apiVersion: v1
kind: Namespace
metadata:
  name: net
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: net-mysql-pvc
  namespace: net
spec:
  storageClassName: nfs-csi-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-content-pvc
  namespace: net
spec:
  storageClassName: nfs-csi-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: private-content-pvc
  namespace: net
spec:
  storageClassName: nfs-csi-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi